use_frameworks!
platform :ios, '9.0'
inhibit_all_warnings!
install! 'cocoapods', :deterministic_uuids => false

source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitee.com/vinny/MLSpecs.git'

target 'MLRefreshSDK_Example' do
  pod 'MLRefreshSDK', :path => '../'

  target 'MLRefreshSDK_Tests' do
    inherit! :search_paths

    
  end
end
